# -*- coding: utf-8 -*-
"""A090D109 1005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154dsihS5CyL0YhsviQqwO4XoUEf12mP8

# HASH 雜湊函數
- md5
- sha1



- linux指令
- md5sum
- Colab使用方式 : !md5sum 檔案名稱
"""

!md5sum --help

!echo A090D109 > 1005.txt

!cat 1005.txt

!md5sum 1005.txt

!echo A090d109 > 1005a.txt

!cat 1005a.txt

!md5sum 1005a.txt